
/*------------------------------------------------------------
Copyright (C) 2007 SAS Institute, Inc. All rights reserved.

Notice:
  The following permissions are granted provided that the
  above copyright and this notice appear in the code and
  any related documentation. Permission to copy, modify
  and distribute the C language source code generated using
  or distributed with SAS Enterprise Miner C scoring component
  and any executables derived from such source code is
  limited to customers of SAS Institute with a valid license
  for SAS Enterprise Miner software. Any distribution
  of such executables or source code shall be on an "AS IS"
  basis without warranty of any kind.  SAS and all other SAS
  Institute. Inc. product and service names are registered
  trademarks or trademarks of SAS Institute Inc. in the USA
  and other countries. Except as contained in this notice,
  the name of the SAS Institute, SAS Enterprise Miner and
  SAS Enterprise Miner Cscore software shall not be used in
  the advertising or promotion of products or services without
  prior written authorization from SAS Institute Inc.
------------------------------------------------------------*/
/*-----------------------------------------------------------------
 *
 *  This is file defines the structures and types used to call the
 *  score function generated by SAS/Enterprise Miner C*Score product.
 *
 *  Product:     SAS Enterprise Miner C*Score
 *  Author:      SAS Institute
 *  Date:        March 29, 2007
 *
 *------------------------------------------------------------------*/
#ifndef CSCORE_PARM_H
#define CSCORE_PARM_H  1
enum typetag { char_type,     /* for data of type char *            */
               inum_type,     /* for data of integral type          */
               fnum_type};    /* for data of floating point type    */

struct parmdata {
   union { char * str;
           long   inum;
           double fnum; } data;
    int  datalen;              /* optional length of data field      */
    enum typetag type;         /* optional type of data field        */
    short flag;                /* optional flag field                */
};

typedef struct parmdata PARM;

#endif
