CREATE TABLE URL (
  URL_ID    NUMBER(19,0)   NOT NULL, --SEQ_URL_ID
  CODE 		VARCHAR2(6)   NOT NULL UNIQUE, 
  URL         	VARCHAR2(255) NOT NULL,
  CREATE_TIME TIMESTAMP    NOT NULL,
  SYS_ID NUMBER(2,0)   NOT NULL,  
  CUST_ID NUMBER(2,0)    NULL, 
  TRACE_CODE NUMBER(2,0)   NULL, 
  PRIMARY KEY (URL_ID)
);

CREATE TABLE URL_VISIT_LOG (
	CODE     VARCHAR2(11)  NOT NULL UNIQUE,
  	CUST_ID NUMBER(2,0)    NULL, 
  	TRACE_CODE NUMBER(2,0)   NULL,
   	VISIT_TIME TIMESTAMP    NOT NULL,
   	IP VARCHAR2(15)   NOT NULL UNIQUE, 
   	User_Agent VARCHAR2(255) NOT NULL,
   	Cookie VARCHAR2(255) NOT NULL,
);

CREATE SEQUENCE SEQ_URL_ID
MINVALUE 1
--MAXVALUE 9223372036854775807 -- 最大值Long.MAX_VALUE
MAXVALUE 56800235583 -- 最大值62*62*62*62*62*62
INCREMENT BY 1 -- 每次加几个
START WITH 1 -- 从1开始计数
CYCLE -- 循环
CACHE 10; --缓存10个序列

SELECT SEQ_URLS_ID.NEXTVAL FROM DUAL;
